import os
import requests
import json

OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
PR_NUMBER = os.environ.get("PR_NUMBER")
REPO = os.environ.get("REPO")

def get_pr_diff():
    url = f"https://api.github.com/repos/{REPO}/pulls/{PR_NUMBER}/files"
    headers = {"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github.v3+json"}
    res = requests.get(url, headers=headers)
    files = res.json()
    diff = ""
    for f in files:
        diff += f"\n--- {f['filename']} ---\n"
        diff += f.get("patch", "")
    return diff

def ai_review(diff):
    prompt = f"""You are a senior software engineer doing a code review. 
Review the following code diff and provide constructive feedback.
Focus on: code quality, potential bugs, security issues, performance, and best practices.
Be specific and actionable. Keep it under 300 words.

Code Diff:
{diff}"""

    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://github.com",
        "X-Title": "CI-CD-AI-Review"
    }
    payload = {
        "model": "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
        "messages": [{"role": "user", "content": prompt}]
    }
    res = requests.post("https://openrouter.ai/api/v1/chat/completions", headers=headers, json=payload)
    result = res.json()
    return result["choices"][0]["message"]["content"]

def post_comment(review):
    url = f"https://api.github.com/repos/{REPO}/issues/{PR_NUMBER}/comments"
    headers = {"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github.v3+json"}
    body = f"## AI Code Review\n\n{review}\n\n---\n*Generated by AI Code Reviewer*"
    requests.post(url, headers=headers, json={"body": body})
    print("AI review posted successfully")

if __name__ == "__main__":
    print("Fetching PR diff...")
    diff = get_pr_diff()
    print("Running AI review...")
    review = ai_review(diff)
    print("Posting comment...")
    post_comment(review)